---
title: "p8105_hw2_cl4776"
author: "Chenxi Liu"
date: "2025-09-30"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

# Problem 1

## clean the data in pols_month.csv

```{r}
litters_df = read_csv("data/pols-month.csv") |> 
   separate(mon, into = c("year", "month", "day"), sep = "-") |>
   mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day),
   
    month = month.name[month],
  
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )
  ) |>
  select(-day, -prez_gop, -prez_dem)
litters_df
```

## clean the data in snp.csv

```{r}
snp = read_csv("data/snp.csv") |>
  mutate(
    date  = mdy(date),
    year  = year(date),
    month_num = month(date),
    month = factor(month.name[month_num], levels = month.name) 
  ) |>
  arrange(year, month_num) |>
  select(year, month, close, -date, -month_num)
snp
```

## Tidy the unemplyment data and merge with previous datasets

```{r}

unemployment = read_csv("data/unemployment.csv") |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month", 
    values_to = "unemployment"
  ) |>
  mutate(
    year = as.integer(Year),
    month = month.name[match(month, month.abb)]
  ) |>
  select(year, month, unemployment) |>
  arrange(year, match(month, month.name))
unemployment
```

